export type ProjectInput = {
  Title: string;
  approvalYear?: number;
  budgetBrl?: number;
  status?: string;
  investmentLevel?: string;
  fundingSource?: string;
  program?: string;
  company?: string;
  center?: string;
  unit?: string;
  location?: string;
  depreciationCostCenter?: string;
  category?: string;
  investmentType?: string;
  assetType?: string;
  projectFunction?: string;
  projectLeader?: string;
  projectUser?: string;
  codigoSAP?: string;
  sourceProjectCode?: string;
  hasRoce?: string;
  startDate?: string;
  endDate?: string;
  businessNeed?: string;
  proposedSolution?: string;
  kpiType?: string;
  kpiName?: string;
  kpiDescription?: string;
  kpiCurrent?: string;
  kpiExpected?: string;
  roceGain?: number;
  roceGainDescription?: string;
  roceLoss?: number;
  roceLossDescription?: string;
  roceClassification?: string;
  operationalCategory?: string;
  complexity?: string;
};

export type ProjectView = ProjectInput & { Id: number };
